"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

interface OnboardingWizardClientProps {
  apiHost: string;
  defaultDevKey: string;
}

export default function OnboardingWizardClient({
  apiHost,
  defaultDevKey,
}: OnboardingWizardClientProps) {
  const [questions, setQuestions] = useState<string[]>([]);
  const [answers, setAnswers] = useState<{ [key: string]: string }>({});
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  
  const [activeStep, setActiveStep] = useState(0);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isCompleted, setIsCompleted] = useState(false);

  // 1. Fetch AI Generated Onboarding Questions
  useEffect(() => {
    const fetchQuestions = async () => {
      try {
        const response = await fetch(`${apiHost}/api/onboarding/questions`, {
          method: "GET",
          headers: {
            "X-API-Key": defaultDevKey,
          },
        });

        if (response.ok) {
          const data = await response.json();
          // The API returns { "questions": [...] }
          if (data.questions && data.questions.length > 0) {
            setQuestions(data.questions.slice(0, 10)); // Ensure max 10
            
            // Pre-fill answer state map
            const initialAns: { [key: string]: string } = {};
            data.questions.forEach((q: string) => {
              initialAns[q] = "";
            });
            setAnswers(initialAns);
          } else {
            setError("No questions generated by AI. Try uploading another document.");
          }
        } else {
          const errData = await response.json();
          setError(errData.detail || "Failed to retrieve onboarding questions.");
        }
      } catch (err) {
        console.error(err);
        setError("Network error connecting to AI Answer engine. Make sure FastAPI backend is active.");
      } finally {
        setLoading(false);
      }
    };

    fetchQuestions();
  }, [apiHost, defaultDevKey]);

  const handleAnswerChange = (text: string) => {
    const currentQ = questions[activeStep];
    setAnswers((prev) => ({
      ...prev,
      [currentQ]: text,
    }));
  };

  const handleNext = () => {
    if (activeStep < questions.length - 1) {
      setActiveStep((prev) => prev + 1);
    }
  };

  const handleBack = () => {
    if (activeStep > 0) {
      setActiveStep((prev) => prev - 1);
    }
  };

  // 2. Submit Q&A Pairs to Vector Database
  const handleSubmit = async () => {
    setIsSubmitting(true);
    try {
      const response = await fetch(`${apiHost}/api/onboarding/answers`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-API-Key": defaultDevKey,
        },
        body: JSON.stringify({ answers }),
      });

      if (response.ok) {
        setIsCompleted(true);
      } else {
        alert("Failed to submit answers. Please try again.");
      }
    } catch (err) {
      console.error(err);
      alert("Network error submitting Q&A pairs to vector database.");
    } finally {
      setIsSubmitting(false);
    }
  };

  if (loading) {
    return (
      <div className="glass-panel p-8 rounded-xl text-center max-w-xl mx-auto py-20 flex flex-col items-center">
        {/* Loading Spinner */}
        <div className="relative w-16 h-16 mb-6">
          <div className="absolute top-0 left-0 w-full h-full rounded-full border-4 border-slate-800" />
          <div className="absolute top-0 left-0 w-full h-full rounded-full border-4 border-t-violet-500 border-r-indigo-500 animate-spin" />
        </div>
        <h3 className="text-lg font-bold text-white mb-2">Analyzing Knowledge base...</h3>
        <p className="text-xs text-gray-500 max-w-sm leading-relaxed animate-pulse">
          Verdia AI is reading your document text context and generating 10 custom, high-probability customer questions. This can take up to 15 seconds.
        </p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="glass-panel p-8 rounded-xl text-center max-w-xl mx-auto py-16 flex flex-col items-center">
        <div className="p-3 bg-red-950/40 border border-red-800/40 rounded-full text-red-400 mb-4">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
        </div>
        <h3 className="text-md font-bold text-white mb-2">Onboarding Question Generation Failed</h3>
        <p className="text-xs text-red-300 max-w-sm mb-6">{error}</p>
        <Link
          href="/dashboard/kb"
          className="px-4 py-2 bg-slate-900 border border-slate-800 hover:bg-slate-800 text-white rounded-lg text-xs font-semibold transition"
        >
          Return to Knowledge Base
        </Link>
      </div>
    );
  }

  if (isCompleted) {
    return (
      <div className="glass-panel p-8 rounded-xl text-center max-w-xl mx-auto py-16 flex flex-col items-center">
        <div className="p-4 bg-emerald-950/40 rounded-full border border-emerald-800/40 text-emerald-400 mb-6 animate-bounce">
          <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg>
        </div>
        <h3 className="text-xl font-bold text-white mb-2">Onboarding Seed Completed! 🎉</h3>
        <p className="text-sm text-gray-400 max-w-sm mb-8 leading-relaxed">
          Your custom Q&A answers have been embedded and injected as **High-Priority knowledge vectors** in Qdrant database storage. 
        </p>
        <div className="flex gap-4">
          <Link
            href="/dashboard/customizer"
            className="px-5 py-3 rounded-lg bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-500 hover:to-indigo-500 text-white font-semibold text-xs transition shadow-lg shadow-indigo-600/10 glow-btn"
          >
            Launch Live Customizer
          </Link>
          <Link
            href="/dashboard"
            className="px-5 py-3 rounded-lg bg-slate-900 border border-slate-800 hover:bg-slate-800 text-gray-300 font-semibold text-xs transition"
          >
            Go to Dashboard
          </Link>
        </div>
      </div>
    );
  }

  const currentQuestion = questions[activeStep];
  const progressPercent = Math.round(((activeStep + 1) / questions.length) * 100);

  return (
    <div className="max-w-2xl mx-auto">
      {/* Progress Bar Header */}
      <div className="mb-8">
        <div className="flex justify-between items-center mb-2">
          <span className="text-xs font-semibold text-gray-400 uppercase tracking-wider">
            Question {activeStep + 1} of {questions.length}
          </span>
          <span className="text-xs font-bold text-violet-400">{progressPercent}%</span>
        </div>
        <div className="w-full h-1.5 bg-slate-900 border border-slate-800/80 rounded-full overflow-hidden">
          <div
            className="h-full bg-gradient-to-r from-violet-500 to-indigo-500 rounded-full transition-all duration-300"
            style={{ width: `${progressPercent}%` }}
          />
        </div>
      </div>

      {/* Main Form Question Card */}
      <div className="glass-panel p-8 rounded-xl relative overflow-hidden space-y-6">
        <div className="absolute top-0 left-0 w-1.5 h-full bg-gradient-to-b from-violet-600 to-indigo-600" />
        
        <div>
          <span className="px-2 py-0.5 rounded bg-violet-950/40 border border-violet-800/40 text-[10px] uppercase font-bold tracking-wider text-violet-300">
            AI Generated Query Prompt
          </span>
          <h3 className="text-lg font-bold text-white mt-3 leading-snug">
            "{currentQuestion}"
          </h3>
        </div>

        <div className="space-y-2">
          <label className="text-xs font-semibold text-gray-400 uppercase tracking-wider">Configure Ideal Response</label>
          <textarea
            required
            rows={4}
            value={answers[currentQuestion] || ""}
            onChange={(e) => handleAnswerChange(e.target.value)}
            placeholder="Type your business's ideal answer. If not specified, the AI will use this seeding response as ground truth context."
            className="w-full bg-slate-900/60 border border-slate-800 rounded-lg p-4 text-sm text-white placeholder-slate-500 focus:outline-none focus:border-violet-600 focus:ring-1 focus:ring-violet-600 transition resize-none"
          />
        </div>

        {/* Action Buttons */}
        <div className="flex justify-between items-center pt-4 border-t border-slate-800/80">
          <button
            type="button"
            onClick={handleBack}
            disabled={activeStep === 0 || isSubmitting}
            className={`px-4 py-2.5 rounded-lg text-xs font-semibold transition flex items-center gap-1.5 ${
              activeStep === 0
                ? "text-gray-600 cursor-not-allowed"
                : "text-gray-300 bg-slate-900 border border-slate-800 hover:bg-slate-800"
            }`}
          >
            ← Previous
          </button>

          {activeStep < questions.length - 1 ? (
            <button
              type="button"
              onClick={handleNext}
              disabled={isSubmitting}
              className="px-5 py-2.5 rounded-lg bg-slate-900 border border-slate-800 hover:bg-slate-800 text-white font-semibold text-xs transition"
            >
              Next Question -&gt;
            </button>
          ) : (
            <button
              type="button"
              onClick={handleSubmit}
              disabled={isSubmitting}
              className="px-6 py-2.5 bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-500 hover:to-indigo-500 text-white font-bold rounded-lg text-xs transition duration-200 transform active:scale-95 shadow-lg shadow-indigo-600/10 glow-btn"
            >
              {isSubmitting ? "Seeding..." : "Finish & Ingest Knowledge 🎉"}
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
